stages:
  - build and deploy doc
  - build package as artifact


pages:
  stage: build and deploy doc
  image: python:3.8-slim
  script:
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install -r requirements.txt
  - sphinx-build -b singlehtml build-docs/ docs/
  - mv docs public
  only:
  - main


package:
  image: python:3.8-slim
  stage: build package as artifact
  script:
  - pip install setuptools
  - python3 -m setup bdist_wheel
  artifacts:
    paths:
    - dist
    expire_in: 120 seconds
  only:
  - main


  
