image: python:3.8-slim

pages:
  script:
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install -r requirements.txt
  - sphinx-build -b singlehtml build-docs/ docs/
  - mv docs public
  artifacts:
    paths:
    - public
    expire_in: 60 seconds
  only:
  - main


build:
  script:
    - pip install setuptools
    - python3 -m setup bdist_wheel
  artifacts:
    paths:
    - dist
    expire_in: 30 seconds
  only:
  - main

  
