image: python:3.8-slim

pages:
  script:
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install -r requirements.txt
  - sphinx-build -b singlehtml build-docs/ docs/
  - mv docs public
  - pip install setuptools
  - pip install build
  - build
  artifacts:
    paths:
    - public
    expire_in: 60 seconds
  only:
  - main
